# Generated by Django 5.1.6 on 2025-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
